"""Rename photo_file_id to photo_file_ids

Revision ID: 14a85afee594
Revises: 6a5ba79dd7fa
Create Date: 2026-01-02 16:57:14.180835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a85afee594'
down_revision: Union[str, None] = '6a5ba79dd7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add new column as nullable first
    op.add_column('flight_cargos', sa.Column('photo_file_ids', sa.Text(), nullable=True, comment='JSON array of Telegram photo file IDs'))

    # Step 2: Migrate data - convert old photo_file_id to JSON array format
    op.execute("""
        UPDATE flight_cargos
        SET photo_file_ids = '["' || photo_file_id || '"]'
        WHERE photo_file_id IS NOT NULL
    """)

    # Step 3: Set default for any null values (shouldn't exist but just in case)
    op.execute("""
        UPDATE flight_cargos
        SET photo_file_ids = '[]'
        WHERE photo_file_ids IS NULL
    """)

    # Step 4: Make column NOT NULL now that all data is migrated
    op.alter_column('flight_cargos', 'photo_file_ids', nullable=False)

    # Step 5: Drop old column
    op.drop_column('flight_cargos', 'photo_file_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_cargos', sa.Column('photo_file_id', sa.TEXT(), autoincrement=False, nullable=False, comment='Telegram photo file ID for storage and retrieval'))
    op.drop_column('flight_cargos', 'photo_file_ids')
    # ### end Alembic commands ###
