"""add_is_sent_web_columns

Revision ID: 21a5e3ebcf9b
Revises: 8e33fda0e04a
Create Date: 2026-02-17 15:28:15.241572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a5e3ebcf9b'
down_revision: Union[str, None] = '8e33fda0e04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_cargos', sa.Column('is_sent_web', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether this cargo has been sent via web interface'))
    op.add_column('flight_cargos', sa.Column('is_sent_web_date', sa.DateTime(), nullable=True, comment='Date/time when cargo was sent via web interface'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight_cargos', 'is_sent_web_date')
    op.drop_column('flight_cargos', 'is_sent_web')
    # ### end Alembic commands ###
