"""Add CargoItem model for import functionality

Revision ID: 261a5556abe0
Revises: db56c0a15183
Create Date: 2025-12-28 11:48:12.678698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261a5556abe0'
down_revision: Union[str, None] = 'db56c0a15183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_name', sa.String(length=100), nullable=True),
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('track_code', sa.String(length=100), nullable=True),
    sa.Column('total_weight', sa.String(length=100), nullable=True),
    sa.Column('item_name_cn', sa.String(length=100), nullable=True),
    sa.Column('item_name_ru', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('weight_kg', sa.String(length=100), nullable=True),
    sa.Column('price_per_kg', sa.String(length=100), nullable=True),
    sa.Column('total_payment', sa.String(length=100), nullable=True),
    sa.Column('box_number', sa.String(length=100), nullable=True),
    sa.Column('checkin_status', sa.String(length=10), nullable=False, comment='pre=CHINA, post=UZBEKISTAN'),
    sa.Column('pre_checkin_date', sa.String(length=100), nullable=True),
    sa.Column('post_checkin_date', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_items_client_id'), 'cargo_items', ['client_id'], unique=False)
    op.create_index(op.f('ix_cargo_items_track_code'), 'cargo_items', ['track_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cargo_items_track_code'), table_name='cargo_items')
    op.drop_index(op.f('ix_cargo_items_client_id'), table_name='cargo_items')
    op.drop_table('cargo_items')
    # ### end Alembic commands ###
