"""add_admin_rbac_tables

Revision ID: 35161f60472f
Revises: a77016dce115
Create Date: 2026-03-18 23:01:22.867136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35161f60472f'
down_revision: Union[str, None] = 'a77016dce115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource', 'action', name='uq_permission_resource_action')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('admin_accounts',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('system_username', sa.String(length=64), nullable=False, comment='Username used for admin panel login (not Telegram username)'),
    sa.Column('pin_hash', sa.String(length=256), nullable=False, comment='bcrypt hash of the 4-digit (or longer) PIN'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='If set and in the future, logins are rejected until this time'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-disable an admin account without deleting it'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_accounts_client_id'), 'admin_accounts', ['client_id'], unique=True)
    op.create_index(op.f('ix_admin_accounts_role_id'), 'admin_accounts', ['role_id'], unique=False)
    op.create_index(op.f('ix_admin_accounts_system_username'), 'admin_accounts', ['system_username'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('admin_audit_logs',
    sa.Column('admin_account_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_account_id'], ['admin_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_admin_account_id'), 'admin_audit_logs', ['admin_account_id'], unique=False)
    op.create_table('admin_passkeys',
    sa.Column('admin_account_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=512), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_account_id'], ['admin_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_passkeys_admin_account_id'), 'admin_passkeys', ['admin_account_id'], unique=False)
    op.create_index(op.f('ix_admin_passkeys_credential_id'), 'admin_passkeys', ['credential_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_passkeys_credential_id'), table_name='admin_passkeys')
    op.drop_index(op.f('ix_admin_passkeys_admin_account_id'), table_name='admin_passkeys')
    op.drop_table('admin_passkeys')
    op.drop_index(op.f('ix_admin_audit_logs_admin_account_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_admin_accounts_system_username'), table_name='admin_accounts')
    op.drop_index(op.f('ix_admin_accounts_role_id'), table_name='admin_accounts')
    op.drop_index(op.f('ix_admin_accounts_client_id'), table_name='admin_accounts')
    op.drop_table('admin_accounts')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
