"""Add broadcast_messages table

Revision ID: 439e07b6800b
Revises: d8f2a1b5c3e7
Create Date: 2026-01-04 00:08:39.934969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439e07b6800b'
down_revision: Union[str, None] = 'd8f2a1b5c3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by_telegram_id', sa.Integer(), nullable=False, comment='Telegram ID of admin who created this broadcast'),
    sa.Column('media_type', sa.Enum('TEXT', 'PHOTO', 'PHOTO_ALBUM', 'VIDEO', 'VIDEO_ALBUM', 'DOCUMENT', 'DOCUMENT_ALBUM', 'AUDIO', 'AUDIO_ALBUM', 'VOICE', 'FORWARD', name='broadcastmediatype'), nullable=False, comment='Type of media content'),
    sa.Column('caption', sa.Text(), nullable=True, comment='Message caption/text'),
    sa.Column('media_file_ids', sa.Text(), nullable=True, comment='JSON array of Telegram file_id or single file_id'),
    sa.Column('forward_from_chat_id', sa.Integer(), nullable=True, comment='Chat ID to forward from'),
    sa.Column('forward_message_id', sa.Integer(), nullable=True, comment='Message ID to forward'),
    sa.Column('inline_buttons', sa.Text(), nullable=True, comment='JSON array of inline keyboard buttons'),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'SENDING', 'COMPLETED', 'CANCELLED', 'FAILED', name='broadcaststatus'), nullable=False, comment='Current status of broadcast'),
    sa.Column('total_users', sa.Integer(), nullable=False, comment='Total number of users to send to'),
    sa.Column('sent_count', sa.Integer(), nullable=False, comment='Number of successfully sent messages'),
    sa.Column('failed_count', sa.Integer(), nullable=False, comment='Number of failed sends'),
    sa.Column('blocked_count', sa.Integer(), nullable=False, comment='Number of users who blocked the bot'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When broadcast was created'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='When sending started'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='When sending completed'),
    sa.Column('pin_message', sa.Boolean(), nullable=False, comment='Whether to pin the message for users'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broadcast_messages')
    # ### end Alembic commands ###
