"""Add flight_cargos table with is_sent tracking

Revision ID: 6a5ba79dd7fa
Revises: 71da0f7fb9d2
Create Date: 2026-01-01 15:22:14.964801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a5ba79dd7fa'
down_revision: Union[str, None] = '71da0f7fb9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop flights table and index if they exist
    op.execute("DROP INDEX IF EXISTS ix_flights_code")
    op.execute("DROP TABLE IF EXISTS flights CASCADE")

    # Add new columns to flight_cargos
    op.add_column('flight_cargos', sa.Column('flight_name', sa.String(length=100), nullable=False, comment='Flight/Reys name from Google Sheets (e.g., M123-2025)', server_default=''))
    op.add_column('flight_cargos', sa.Column('is_sent', sa.Boolean(), nullable=False, comment='Whether this cargo photo has been sent to the client', server_default='false'))

    # Remove server defaults after adding columns
    op.alter_column('flight_cargos', 'flight_name', server_default=None)
    op.alter_column('flight_cargos', 'is_sent', server_default=None)

    # Update column comments
    op.alter_column('flight_cargos', 'client_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Client code (e.g., SS123, AD456)',
               existing_comment='Client code (e.g., SS123)',
               existing_nullable=False)
    op.alter_column('flight_cargos', 'photo_file_id',
               existing_type=sa.TEXT(),
               comment='Telegram photo file ID for storage and retrieval',
               existing_comment='Telegram photo file ID',
               existing_nullable=False)

    # Drop old indexes and constraints if they exist
    op.execute("DROP INDEX IF EXISTS ix_flight_cargo_flight_client")
    op.execute("DROP INDEX IF EXISTS ix_flight_cargos_flight_id")
    op.execute("ALTER TABLE flight_cargos DROP CONSTRAINT IF EXISTS flight_cargos_flight_id_fkey")

    # Create new indexes
    op.create_index('ix_flight_cargos_flight_client', 'flight_cargos', ['flight_name', 'client_id'], unique=False)
    op.create_index(op.f('ix_flight_cargos_flight_name'), 'flight_cargos', ['flight_name'], unique=False)
    op.create_index(op.f('ix_flight_cargos_is_sent'), 'flight_cargos', ['is_sent'], unique=False)

    # Drop old flight_id column if it exists
    op.execute("ALTER TABLE flight_cargos DROP COLUMN IF EXISTS flight_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flight_cargos', sa.Column('flight_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Reference to flight'))
    op.create_foreign_key('flight_cargos_flight_id_fkey', 'flight_cargos', 'flights', ['flight_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_flight_cargos_is_sent'), table_name='flight_cargos')
    op.drop_index(op.f('ix_flight_cargos_flight_name'), table_name='flight_cargos')
    op.drop_index('ix_flight_cargos_flight_client', table_name='flight_cargos')
    op.create_index('ix_flight_cargos_flight_id', 'flight_cargos', ['flight_id'], unique=False)
    op.create_index('ix_flight_cargo_flight_client', 'flight_cargos', ['flight_id', 'client_id'], unique=False)
    op.alter_column('flight_cargos', 'photo_file_id',
               existing_type=sa.TEXT(),
               comment='Telegram photo file ID',
               existing_comment='Telegram photo file ID for storage and retrieval',
               existing_nullable=False)
    op.alter_column('flight_cargos', 'client_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Client code (e.g., SS123)',
               existing_comment='Client code (e.g., SS123, AD456)',
               existing_nullable=False)
    op.drop_column('flight_cargos', 'is_sent')
    op.drop_column('flight_cargos', 'flight_name')
    op.create_table('flights',
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Flight code (e.g., HY123)'),
    sa.Column('flight_date', sa.DATE(), autoincrement=False, nullable=True, comment='Date of the flight'),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Flight description'),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Is flight currently active'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='flights_pkey')
    )
    op.create_index('ix_flights_code', 'flights', ['code'], unique=True)
    # ### end Alembic commands ###
