"""add flight and flight_cargo tables

Revision ID: 71da0f7fb9d2
Revises: b6800d2bc2e1
Create Date: 2026-01-01 02:33:05.973839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71da0f7fb9d2'
down_revision: Union[str, None] = 'b6800d2bc2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Flight code (e.g., HY123)'),
    sa.Column('flight_date', sa.Date(), nullable=True, comment='Date of the flight'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Flight description'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is flight currently active'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_code'), 'flights', ['code'], unique=True)
    op.create_table('flight_cargos',
    sa.Column('flight_id', sa.Integer(), nullable=False, comment='Reference to flight'),
    sa.Column('client_id', sa.String(length=50), nullable=False, comment='Client code (e.g., SS123)'),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=True, comment='Weight in kilograms'),
    sa.Column('photo_file_id', sa.Text(), nullable=False, comment='Telegram photo file ID'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Optional comment or notes'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flight_cargo_flight_client', 'flight_cargos', ['flight_id', 'client_id'], unique=False)
    op.create_index(op.f('ix_flight_cargos_client_id'), 'flight_cargos', ['client_id'], unique=False)
    op.create_index(op.f('ix_flight_cargos_flight_id'), 'flight_cargos', ['flight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_cargos_flight_id'), table_name='flight_cargos')
    op.drop_index(op.f('ix_flight_cargos_client_id'), table_name='flight_cargos')
    op.drop_index('ix_flight_cargo_flight_client', table_name='flight_cargos')
    op.drop_table('flight_cargos')
    op.drop_index(op.f('ix_flights_code'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
