"""Add payment_receipt_file_id and taken_away fields to client_transaction_data

Revision ID: 835436ce54d5
Revises: 541e4bddd45a
Create Date: 2025-12-30 10:04:05.697335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835436ce54d5'
down_revision: Union[str, None] = '541e4bddd45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_transaction_data', sa.Column('payment_receipt_file_id', sa.String(length=255), nullable=True, comment='Telegram file_id of payment receipt (photo or PDF)'))
    op.add_column('client_transaction_data', sa.Column('is_taken_away', sa.Boolean(), server_default='false', nullable=False, comment='Whether cargo has been taken away by client'))
    op.add_column('client_transaction_data', sa.Column('taken_away_date', sa.DateTime(timezone=True), nullable=True, comment='Date when cargo was taken away'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_transaction_data', 'taken_away_date')
    op.drop_column('client_transaction_data', 'is_taken_away')
    op.drop_column('client_transaction_data', 'payment_receipt_file_id')
    # ### end Alembic commands ###
