"""add_user_details_to_session_logs

Revision ID: 8e33fda0e04a
Revises: 19d9be761e4c
Create Date: 2026-02-03 14:44:37.273040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e33fda0e04a'
down_revision: Union[str, None] = '19d9be761e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema (safe & idempotent)."""

    # ---- Safe index drops ----
    op.execute("DROP INDEX IF EXISTS idx_delivery_requests_client_id")
    op.execute("DROP INDEX IF EXISTS idx_delivery_requests_status")
    op.execute("DROP INDEX IF EXISTS idx_delivery_requests_telegram_id")
    op.execute("DROP INDEX IF EXISTS ix_client_payment_events_provider")
    op.execute("DROP INDEX IF EXISTS ix_client_payment_events_tx_created")
    op.execute("DROP INDEX IF EXISTS ix_client_payment_events_tx_provider")
    op.execute("DROP INDEX IF EXISTS idx_clients_telegram_id_not_null")

    # ---- Safe table drop ----
    op.execute("DROP TABLE IF EXISTS delivery_requests CASCADE")

    # ---- Alter columns (comments cleanup) ----
    op.alter_column(
        "analytics_events",
        "created_at",
        comment=None,
        existing_type=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )

    op.alter_column(
        "analytics_events",
        "updated_at",
        comment=None,
        existing_type=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )

    op.alter_column(
        "api_request_logs",
        "created_at",
        comment=None,
        existing_type=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )

    op.alter_column(
        "api_request_logs",
        "updated_at",
        comment=None,
        existing_type=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )

    op.alter_column(
        "client_transaction_data",
        "payment_type",
        comment="Payment type: 'online', 'cash', or 'card'",
        existing_type=sa.VARCHAR(length=10),
        existing_nullable=False,
        existing_server_default=sa.text("'online'::character varying"),
    )

    # ---- Add new columns ----
    op.add_column("session_logs", sa.Column("client_code", sa.String(20), nullable=True))
    op.add_column("session_logs", sa.Column("phone", sa.String(30), nullable=True))
    op.add_column("session_logs", sa.Column("username", sa.String(100), nullable=True))

    # ---- Make static_data fields NOT NULL ----
    op.alter_column("static_data", "foto_hisobot", nullable=False)
    op.alter_column("static_data", "extra_charge", nullable=False)
    op.alter_column("static_data", "price_per_kg", nullable=False)
    op.alter_column("static_data", "notification_period", nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats_daily_payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when stat was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('stats_daily_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when stat was created',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('stats_daily_clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when stat was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('stats_daily_clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when stat was created',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('stats_daily_cargo', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when stat was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('stats_daily_cargo', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when stat was created',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('static_data', 'notification_period',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='How often (in DAYS) notifications are sent (1-15 days)')
    op.alter_column('static_data', 'price_per_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_comment='Price per kilogram (e.g., 9.2, 10.4)')
    op.alter_column('static_data', 'extra_charge',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='Extra charge amount')
    op.alter_column('static_data', 'foto_hisobot',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='Photo report template text')
    op.drop_column('session_logs', 'username')
    op.drop_column('session_logs', 'phone')
    op.drop_column('session_logs', 'client_code')
    op.create_index('idx_clients_telegram_id_not_null', 'clients', ['telegram_id'], unique=False, postgresql_where='(telegram_id IS NOT NULL)')
    op.alter_column('client_transaction_data', 'payment_type',
               existing_type=sa.VARCHAR(length=10),
               comment="Payment type: 'online' or 'cash'",
               existing_comment="Payment type: 'online', 'cash', or 'card'",
               existing_nullable=False,
               existing_server_default=sa.text("'online'::character varying"))
    op.create_index('ix_client_payment_events_tx_provider', 'client_payment_events', ['transaction_id', 'payment_provider'], unique=False)
    op.create_index('ix_client_payment_events_tx_created', 'client_payment_events', ['transaction_id', 'created_at'], unique=False)
    op.create_index('ix_client_payment_events_provider', 'client_payment_events', ['payment_provider'], unique=False)
    op.alter_column('client_payment_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='Timestamp when payment event was last updated')
    op.alter_column('client_payment_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the payment event was created',
               existing_comment='Timestamp when payment event was created',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('api_request_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when log was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('api_request_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when request was logged',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('analytics_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when event was last updated',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('analytics_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when event was created',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('delivery_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('delivery_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='uzpost, yandex, akb, bts'),
    sa.Column('flight_names', sa.TEXT(), autoincrement=False, nullable=False, comment='JSON array of flight names'),
    sa.Column('full_name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('prepayment_receipt_file_id', sa.TEXT(), autoincrement=False, nullable=True, comment='File ID of prepayment receipt for UZPOST'),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False, comment='pending, approved, rejected'),
    sa.Column('admin_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_by_admin_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='delivery_requests_pkey')
    )
    op.create_index('idx_delivery_requests_telegram_id', 'delivery_requests', ['telegram_id'], unique=False)
    op.create_index('idx_delivery_requests_status', 'delivery_requests', ['status'], unique=False)
    op.create_index('idx_delivery_requests_client_id', 'delivery_requests', ['client_id'], unique=False)
    # ### end Alembic commands ###
