"""Add notifications table

Revision ID: a77016dce115
Revises: f3c591793b10
Create Date: 2026-03-12 02:11:19.545577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a77016dce115'
down_revision: Union[str, None] = 'f3c591793b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carousel_items',
    sa.Column('type', sa.String(length=20), nullable=False, comment="Item type: 'ad' or 'feature'"),
    sa.Column('title', sa.String(length=256), nullable=True, comment='Display title'),
    sa.Column('sub_title', sa.String(length=512), nullable=True, comment='Display subtitle'),
    sa.Column('media_type', sa.String(length=20), nullable=False, comment="Media type: 'image', 'video', or 'gif'"),
    sa.Column('media_url', sa.String(length=1024), nullable=False, comment='URL to the media file'),
    sa.Column('action_url', sa.String(length=1024), nullable=True, comment='URL to open when item is clicked'),
    sa.Column('text_color', sa.String(length=20), nullable=False, comment='Text color hex code'),
    sa.Column('gradient', sa.String(length=512), nullable=True, comment='CSS gradient string (for features)'),
    sa.Column('order', sa.Integer(), nullable=False, comment='Display order (ascending)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the item is visible'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carousel_stats',
    sa.Column('carousel_item_id', sa.Integer(), nullable=False, comment='FK to carousel_items.id'),
    sa.Column('views', sa.Integer(), nullable=False, comment='Number of views on this date'),
    sa.Column('clicks', sa.Integer(), nullable=False, comment='Number of clicks on this date'),
    sa.Column('date', sa.Date(), nullable=False, comment='Date of aggregation (YYYY-MM-DD)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carousel_item_id'], ['carousel_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carousel_item_id', 'date', name='uq_carousel_stats_item_date')
    )
    op.create_index('ix_carousel_stats_item_date', 'carousel_stats', ['carousel_item_id', 'date'], unique=False)
    op.create_table('notifications',
    sa.Column('client_id', sa.Integer(), nullable=False, comment='FK to clients.id'),
    sa.Column('title', sa.String(length=512), nullable=False, comment='Notification title'),
    sa.Column('body', sa.Text(), nullable=False, comment='Notification body text'),
    sa.Column('type', sa.String(length=50), nullable=False, comment="Notification type: 'payment', 'info', 'warning', 'cargo'"),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Whether the user has read this notification'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_client_created', 'notifications', ['client_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_client_read', 'notifications', ['client_id', 'is_read'], unique=False)
    op.alter_column('delivery_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_delivery_requests_client_id', table_name='delivery_requests')
    op.drop_index('idx_delivery_requests_telegram_id', table_name='delivery_requests')
    op.create_index(op.f('ix_delivery_requests_client_id'), 'delivery_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_delivery_requests_telegram_id'), 'delivery_requests', ['telegram_id'], unique=False)
    op.alter_column('flight_cargos', 'is_sent_web',
               existing_type=sa.BOOLEAN(),
               comment='Whether this cargo has been sent via web interface',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('flight_cargos', 'is_sent_web_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='Date/time when cargo was sent via web interface',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flight_cargos', 'is_sent_web_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Date/time when cargo was sent via web interface',
               existing_nullable=True)
    op.alter_column('flight_cargos', 'is_sent_web',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether this cargo has been sent via web interface',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_delivery_requests_telegram_id'), table_name='delivery_requests')
    op.drop_index(op.f('ix_delivery_requests_client_id'), table_name='delivery_requests')
    op.create_index('idx_delivery_requests_telegram_id', 'delivery_requests', ['telegram_id'], unique=False)
    op.create_index('idx_delivery_requests_client_id', 'delivery_requests', ['client_id'], unique=False)
    op.alter_column('delivery_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('delivery_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_notifications_client_read', table_name='notifications')
    op.drop_index('ix_notifications_client_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_carousel_stats_item_date', table_name='carousel_stats')
    op.drop_table('carousel_stats')
    op.drop_table('carousel_items')
    # ### end Alembic commands ###
