"""add_extra_code_to_client

Revision ID: aaa632e59528
Revises: 8a1236459a67
Create Date: 2026-02-21 20:58:15.905890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa632e59528'
down_revision: Union[str, None] = '8a1236459a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('extra_code', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'clients', ['extra_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_column('clients', 'extra_code')
    # ### end Alembic commands ###
