"""add custom usd rate

Revision ID: add_custom_usd_rate
Revises: d8f2a1b5c3e7
Create Date: 2026-02-21 12:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_custom_usd_rate"
down_revision = "d8f2a1b5c3e7"
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('static_data', sa.Column('custom_usd_rate', sa.Float(), nullable=True, comment='Custom USD to UZS rate override'))
    op.add_column('static_data', sa.Column('use_custom_rate', sa.Boolean(), server_default='false', nullable=False, comment='Whether to use the custom rate instead of API rate'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('static_data', 'use_custom_rate')
    op.drop_column('static_data', 'custom_usd_rate')
    # ### end Alembic commands ###
