"""add_partner_shipments_temp

Revision ID: c1b8617bbfb4
Revises: f8a9b0c1d2e3
Create Date: 2026-04-11 22:24:00.731974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1b8617bbfb4'
down_revision: Union[str, None] = 'f8a9b0c1d2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_shipments_temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_code', sa.String(length=100), nullable=False),
    sa.Column('client_code', sa.String(length=50), nullable=False),
    sa.Column('flight_name', sa.String(length=50), nullable=False),
    sa.Column('received_date', sa.String(length=50), nullable=False),
    sa.Column('weight_kg', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.String(length=20), nullable=False),
    sa.Column('item_name_ru', sa.String(length=200), nullable=True),
    sa.Column('item_name_cn', sa.String(length=200), nullable=True),
    sa.Column('box_number', sa.String(length=50), nullable=True),
    sa.Column('photo_s3_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_shipments_temp_client_code'), 'partner_shipments_temp', ['client_code'], unique=False)
    op.create_index(op.f('ix_partner_shipments_temp_flight_name'), 'partner_shipments_temp', ['flight_name'], unique=False)
    op.create_index(op.f('ix_partner_shipments_temp_track_code'), 'partner_shipments_temp', ['track_code'], unique=True)
    op.drop_index('ix_expected_cargo_flight_client', table_name='expected_flight_cargos')
    op.drop_index('ix_expected_flight_cargos_client_code', table_name='expected_flight_cargos')
    op.drop_index('ix_expected_flight_cargos_flight_name', table_name='expected_flight_cargos')
    op.drop_index('ix_expected_flight_cargos_track_code', table_name='expected_flight_cargos')
    op.drop_table('expected_flight_cargos')
    op.alter_column('cargo_delivery_proofs', 'transaction_id',
               existing_type=sa.INTEGER(),
               comment='The transaction (cargo row) that was taken away',
               existing_comment='The cargo transaction that was taken away',
               existing_nullable=False)
    op.alter_column('cargo_delivery_proofs', 'delivery_method',
               existing_type=sa.VARCHAR(length=32),
               comment='Delivery method chosen by the warehouse worker: uzpost|bts|akb|yandex',
               existing_comment='uzpost | bts | akb | yandex',
               existing_nullable=False)
    op.alter_column('cargo_delivery_proofs', 'marked_by_admin_id',
               existing_type=sa.INTEGER(),
               comment='AdminAccount that performed the take-away marking',
               existing_comment='Admin who performed the take-away marking',
               existing_nullable=True)
    op.drop_index('ix_carousel_item_media_item_id', table_name='carousel_item_media')
    op.drop_index('ix_carousel_item_media_item_order', table_name='carousel_item_media')
    op.drop_index('ix_client_payment_events_approved_by_admin_id', table_name='client_payment_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_client_payment_events_approved_by_admin_id', 'client_payment_events', ['approved_by_admin_id'], unique=False)
    op.create_index('ix_carousel_item_media_item_order', 'carousel_item_media', ['carousel_item_id', 'order'], unique=False)
    op.create_index('ix_carousel_item_media_item_id', 'carousel_item_media', ['carousel_item_id'], unique=False)
    op.alter_column('cargo_delivery_proofs', 'marked_by_admin_id',
               existing_type=sa.INTEGER(),
               comment='Admin who performed the take-away marking',
               existing_comment='AdminAccount that performed the take-away marking',
               existing_nullable=True)
    op.alter_column('cargo_delivery_proofs', 'delivery_method',
               existing_type=sa.VARCHAR(length=32),
               comment='uzpost | bts | akb | yandex',
               existing_comment='Delivery method chosen by the warehouse worker: uzpost|bts|akb|yandex',
               existing_nullable=False)
    op.alter_column('cargo_delivery_proofs', 'transaction_id',
               existing_type=sa.INTEGER(),
               comment='The cargo transaction that was taken away',
               existing_comment='The transaction (cargo row) that was taken away',
               existing_nullable=False)
    op.create_table('expected_flight_cargos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flight_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Shipment batch / flight name, e.g. M123-2025'),
    sa.Column('client_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Client code — matches Client.extra_code or Client.client_code'),
    sa.Column('track_code', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Globally unique cargo tracking code'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='expected_flight_cargos_pkey'),
    sa.UniqueConstraint('track_code', name='expected_flight_cargos_track_code_key')
    )
    op.create_index('ix_expected_flight_cargos_track_code', 'expected_flight_cargos', ['track_code'], unique=False)
    op.create_index('ix_expected_flight_cargos_flight_name', 'expected_flight_cargos', ['flight_name'], unique=False)
    op.create_index('ix_expected_flight_cargos_client_code', 'expected_flight_cargos', ['client_code'], unique=False)
    op.create_index('ix_expected_cargo_flight_client', 'expected_flight_cargos', ['flight_name', 'client_code'], unique=False)
    op.drop_index(op.f('ix_partner_shipments_temp_track_code'), table_name='partner_shipments_temp')
    op.drop_index(op.f('ix_partner_shipments_temp_flight_name'), table_name='partner_shipments_temp')
    op.drop_index(op.f('ix_partner_shipments_temp_client_code'), table_name='partner_shipments_temp')
    op.drop_table('partner_shipments_temp')
    # ### end Alembic commands ###
