"""add_payment_cards_and_client_transactions

Revision ID: db56c0a15183
Revises: 2025_12_25_bigint
Create Date: 2025-12-26 03:42:26.189114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db56c0a15183'
down_revision: Union[str, None] = '2025_12_25_bigint'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_transaction_data',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('client_code', sa.String(length=20), nullable=False),
    sa.Column('qator_raqami', sa.Integer(), nullable=False, comment='Row number in Google Sheets'),
    sa.Column('reys', sa.String(length=255), nullable=False, comment='Worksheet/flight name'),
    sa.Column('summa', sa.Numeric(precision=12, scale=2), nullable=False, comment='Payment amount'),
    sa.Column('vazn', sa.String(length=100), nullable=False, comment='Weight from row_data[2]'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_transaction_data_client_code'), 'client_transaction_data', ['client_code'], unique=False)
    op.create_index(op.f('ix_client_transaction_data_telegram_id'), 'client_transaction_data', ['telegram_id'], unique=False)
    op.create_table('payment_cards',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number')
    )
    op.drop_constraint('clients_telegram_id_key', 'clients', type_='unique')
    op.drop_index('ix_clients_telegram_id', table_name='clients')
    op.create_index(op.f('ix_clients_telegram_id'), 'clients', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_telegram_id'), table_name='clients')
    op.create_index('ix_clients_telegram_id', 'clients', ['telegram_id'], unique=False)
    op.create_unique_constraint('clients_telegram_id_key', 'clients', ['telegram_id'])
    op.drop_table('payment_cards')
    op.drop_index(op.f('ix_client_transaction_data_telegram_id'), table_name='client_transaction_data')
    op.drop_index(op.f('ix_client_transaction_data_client_code'), table_name='client_transaction_data')
    op.drop_table('client_transaction_data')
    # ### end Alembic commands ###
