"""add role column to clients

Revision ID: f3c591793b10
Revises: 61805b38e868
Create Date: 2026-03-10 17:07:05.406469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c591793b10'
down_revision: Union[str, None] = '61805b38e868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    client_cols = {c["name"] for c in inspector.get_columns("clients")}

    if bind.dialect.has_table(bind, 'temp_avia_codes'):
        op.drop_table('temp_avia_codes')

    if "role" not in client_cols:
        op.add_column('clients', sa.Column('role', sa.String(length=20), nullable=True))

    if "legacy_code" in client_cols:
        op.alter_column('clients', 'legacy_code',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.String(length=20),
                   existing_nullable=True)
        legacy_uq_exists = any(
            "legacy_code" in uq.get("column_names", [])
            for uq in inspector.get_unique_constraints("clients")
        )
        if not legacy_uq_exists:
            op.create_unique_constraint("uq_clients_legacy_code", 'clients', ['legacy_code'])

    if "is_admin" in client_cols:
        op.drop_column('clients', 'is_admin')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint("uq_clients_legacy_code", 'clients', type_='unique')
    op.alter_column('clients', 'legacy_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('clients', 'role')
    op.create_table('temp_avia_codes',
    sa.Column('district_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('district_key', name='temp_avia_codes_pkey')
    )
    # ### end Alembic commands ###
