"""partner masking phase 4d: switch AKB partner prefix from 'A' to 'AKB'

Revision ID: p4a5k6b7p8q9
Revises: p3c4r5d6m7n8
Create Date: 2026-04-26 14:00:00.000000

The actual AKB client_code format renders the full ``AKB`` literal (e.g.
``AKB01-1/5``) rather than the single-letter ``A`` placeholder used in
the original Phase 1 implementation.  Update the partner prefix so the
:class:`PartnerResolver` longest-prefix-match still routes ``AKB...``
codes correctly to the AKB partner row.

This migration only touches the ``partners`` table; client codes are
generated by the (now corrected) generator and the historical data is
imported by the standalone ``scripts/migrate_users_from_sqlite.py``.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "p4a5k6b7p8q9"
down_revision: Union[str, None] = "p3c4r5d6m7n8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        sa.text("UPDATE partners SET prefix = 'AKB' WHERE code = 'AKB'")
    )


def downgrade() -> None:
    op.execute(
        sa.text("UPDATE partners SET prefix = 'A' WHERE code = 'AKB'")
    )
